
import type { Product } from './types'

// A tiny catalog to start. Replace with API later.
export const PRODUCTS: Product[] = [
  {
    id: 'P1001',
    slug: 'galaxy-a54-5g-128',
    name: 'Samsung Galaxy A54 5G (128 GB)',
    brand: 'Samsung',
    category: 'Tech',
    subcategory: 'Mobiles',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop',
    extraImages: [
      'https://images.unsplash.com/photo-1510552776732-01acc9a4c38e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1510557880182-3f8c5f03adab?q=80&w=800&auto=format&fit=crop',
    ],
    quantity: 24,
    price: { original: 34999, discounted: 29999, currency: '₹' },
    specifications: { RAM: '8 GB', Storage: '128 GB', Color: 'Awesome Graphite' },
    shortDescription: 'Bright AMOLED, OIS camera, all‑day battery.',
    description: 'A balanced 5G phone with vibrant display, OIS camera, and reliable performance for daily tasks.',
    features: ['IP67 water resistance', '120Hz display', 'Stereo speakers'],
    tags: ['phone','samsung','android','5g'],
    inventory: { inStock: true, lowStockThreshold: 5 },
    ratings: { average: 4.3, count: 1821 },
    returnPolicy: { eligible: true, duration: 7 },
  },
  {
    id: 'P1002',
    slug: 'wireless-noise-cancelling-headphones',
    name: 'Wireless Noise-Cancelling Headphones',
    brand: 'Sony',
    category: 'Tech',
    subcategory: 'Audio',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 40,
    price: { original: 22990, discounted: 19990, currency: '₹' },
    specifications: { 'Connectivity': 'Bluetooth 5.0', 'Battery Life': '30 hours', 'Color': 'Black' },
    shortDescription: 'Immersive sound, industry-leading noise cancellation.',
    description: 'Experience silence with these headphones featuring dual noise sensor technology. Enjoy up to 30 hours of wireless playback.',
    features: ['Quick charging', 'Touch controls', 'Voice assistant compatible'],
    tags: ['headphones', 'audio', 'sony', 'noise-cancelling'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 5320 },
  },
  {
    id: 'P1003',
    slug: 'thin-and-light-laptop-i5',
    name: 'Thin & Light Laptop (Core i5, 16GB RAM)',
    brand: 'Dell',
    category: 'Tech',
    subcategory: 'Laptops',
    image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 15,
    price: { original: 78990, discounted: 69990, currency: '₹' },
    specifications: { 'Processor': 'Intel Core i5', 'RAM': '16 GB', 'Storage': '512 GB SSD' },
    shortDescription: 'Premium ultrabook for professionals on the go.',
    description: 'A sleek and powerful laptop with a stunning display, long battery life, and robust performance for multitasking.',
    features: ['Fingerprint reader', 'Backlit keyboard', 'Thunderbolt 4'],
    tags: ['laptop', 'ultrabook', 'dell', 'windows'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 890 },
  },
    {
    id: 'P1004',
    slug: 'gaming-laptop-rtx-4060',
    name: 'Gaming Laptop (Ryzen 7, RTX 4060)',
    brand: 'Asus',
    category: 'Tech',
    subcategory: 'Laptops',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 10,
    price: { original: 124990, discounted: 109990, currency: '₹' },
    specifications: { 'Processor': 'AMD Ryzen 7', 'Graphics': 'NVIDIA RTX 4060', 'RAM': '16 GB DDR5' },
    shortDescription: 'High-performance gaming beast with a 144Hz display.',
    description: 'Dominate the game with this powerful gaming laptop, featuring the latest CPU and GPU for an unparalleled experience.',
    features: ['RGB keyboard', 'Advanced cooling system', '144Hz high-refresh rate screen'],
    tags: ['laptop', 'gaming', 'asus', 'rog'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 1250 },
  },
  {
    id: 'P2001',
    slug: 'cotton-kurta-men',
    name: 'Pure Cotton Kurta (Men)',
    brand: 'DesiWear',
    category: 'Fashion',
    subcategory: 'Men-Ethnic',
    image: 'https://images.unsplash.com/photo-1593032228653-25cb157b70a8?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 57,
    price: { original: 1499, discounted: 999, currency: '₹' },
    specifications: { Material: '100% Cotton', Color: 'Ivory', Size: 'S-XXL' },
    shortDescription: 'Breathable daily‑wear kurta with classic fit.',
    description: 'Soft cotton kurta for festivals and daily wear. Pairs well with pajamas or jeans.',
    features: ['Machine washable', 'Lightweight', 'Comfort fit'],
    tags: ['kurta','men','ethnic','fashion'],
    inventory: { inStock: true, lowStockThreshold: 10 },
    ratings: { average: 4.5, count: 640 },
  },
  {
    id: 'P2002',
    slug: 'womens-printed-anarkali-kurta',
    name: 'Women\'s Printed Anarkali Kurta',
    brand: 'EthnicVibes',
    category: 'Fashion',
    subcategory: 'Women-Ethnic',
    image: 'https://images.unsplash.com/photo-1622354223106-24c01798835d?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 35,
    price: { original: 2999, discounted: 1899, currency: '₹' },
    specifications: { 'Material': 'Rayon', 'Sleeve Length': 'Three-Quarter Sleeves', 'Pattern': 'Printed' },
    shortDescription: 'Elegant and vibrant Anarkali kurta for special occasions.',
    description: 'This beautifully printed Anarkali kurta is perfect for weddings and festive events. Made from soft rayon for a comfortable fit.',
    features: ['Flared hem', 'Round neck', 'Lightweight fabric'],
    tags: ['anarkali', 'kurta', 'women', 'ethnic', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 980 },
  },
    {
    id: 'P2003',
    slug: 'mens-casual-denim-shirt',
    name: 'Men\'s Casual Denim Shirt',
    brand: 'UrbanStitch',
    category: 'Fashion',
    subcategory: 'Men-Casual',
    image: 'https://images.unsplash.com/photo-1602293589922-3a5682d3809d?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 75,
    price: { original: 2299, discounted: 1599, currency: '₹' },
    specifications: { 'Material': 'Denim Cotton', 'Fit': 'Slim Fit', 'Sleeve': 'Long Sleeve' },
    shortDescription: 'A timeless denim shirt for a rugged, casual look.',
    description: 'Versatile and stylish, this denim shirt can be worn on its own or layered over a t-shirt for a classic, cool vibe.',
    features: ['Button-front closure', 'Chest pocket', 'Durable fabric'],
    tags: ['shirt', 'denim', 'men', 'casual', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 1500 },
  },
  {
    id: 'P3001',
    slug: 'ashwagandha-capsules-60',
    name: 'Ashwagandha Capsules (60)',
    brand: 'HerbCare',
    category: 'Ayurvedic',
    subcategory: 'Supplements',
    image: 'https://images.unsplash.com/photo-1545249390-6b7f2d0d4d1a?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 120,
    price: { original: 699, discounted: 499, currency: '₹' },
    specifications: { Dose: '1/day', Form: 'Veg capsules' },
    shortDescription: 'Adaptogen for stress support and vitality.',
    description: 'Premium Ashwagandha extract to support stress reduction, energy, and overall well‑being.',
    features: ['No added sugar', 'Gluten‑free', 'Vegan'],
    tags: ['ashwagandha','ayurvedic','supplement'],
    inventory: { inStock: true },
    ratings: { average: 4.1, count: 213 },
  },
   {
    id: 'P3002',
    slug: 'triphala-churna-100g',
    name: 'Triphala Churna (100g)',
    brand: 'HerbCare',
    category: 'Ayurvedic',
    subcategory: 'Herbal-Powders',
    image: 'https://images.unsplash.com/photo-1598870783995-62955132c389?q=80&w=800&auto=format&fit=crop',
    extraImages: [],
    quantity: 80,
    price: { original: 199, currency: '₹' },
    specifications: { 'Ingredients': 'Amla, Baheda, Haritaki', 'Form': 'Powder' },
    shortDescription: 'Classic Ayurvedic formula for digestion and detoxification.',
    description: 'A traditional blend of three fruits, Triphala Churna is renowned for its digestive benefits and gentle cleansing properties.',
    features: ['100% natural ingredients', 'Non-GMO', 'Supports regular bowel movements'],
    tags: ['triphala', 'churna', 'ayurvedic', 'digestion'],
    inventory: { inStock: true },
    ratings: { average: 4.4, count: 450 },
  },
  {
    id: 'P1005',
    slug: 'iphone-15-pro-256gb',
    name: 'Apple iPhone 15 Pro (256 GB)',
    brand: 'Apple',
    category: 'Tech',
    subcategory: 'Mobiles',
    image: 'https://images.unsplash.com/photo-1695026222802-74d3213502af?q=80&w=800&auto=format&fit=crop',
    quantity: 30,
    price: { original: 134900, currency: '₹' },
    specifications: { RAM: '8 GB', Storage: '256 GB', Color: 'Natural Titanium' },
    shortDescription: 'The ultimate iPhone experience with A17 Pro chip.',
    description: 'Featuring a strong and light titanium design, a new Action button, and the powerful A17 Pro chip for next-level performance.',
    features: ['Dynamic Island', 'Pro camera system', 'USB-C connector'],
    tags: ['phone', 'apple', 'iphone', 'ios'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 2500 },
  },
  {
    id: 'P1006',
    slug: 'google-pixel-8-128gb',
    name: 'Google Pixel 8 (128 GB)',
    brand: 'Google',
    category: 'Tech',
    subcategory: 'Mobiles',
    image: 'https://images.unsplash.com/photo-1700236024115-b73a6a5de62b?q=80&w=800&auto=format&fit=crop',
    quantity: 45,
    price: { original: 75999, discounted: 69999, currency: '₹' },
    specifications: { RAM: '8 GB', Storage: '128 GB', Color: 'Obsidian' },
    shortDescription: 'The helpful phone, engineered by Google.',
    description: 'Pixel 8 features the powerful Google Tensor G3 chip, an amazing camera, and all-day battery life.',
    features: ['Magic Eraser', 'Live Translate', 'Extreme Battery Saver'],
    tags: ['phone', 'google', 'pixel', 'android'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 1980 },
  },
  {
    id: 'P1007',
    slug: 'macbook-air-m2-256gb',
    name: 'Apple MacBook Air M2 (256 GB)',
    brand: 'Apple',
    category: 'Tech',
    subcategory: 'Laptops',
    image: 'https://images.unsplash.com/photo-1662996370338-b5b63517c461?q=80&w=800&auto=format&fit=crop',
    quantity: 20,
    price: { original: 114900, discounted: 104900, currency: '₹' },
    specifications: { Chip: 'Apple M2', RAM: '8 GB', Storage: '256 GB SSD' },
    shortDescription: 'Supercharged by the M2 chip. Incredibly thin and light.',
    description: 'The MacBook Air with the M2 chip is redesigned around the next-generation M2 chip, it’s strikingly thin and brings exceptional speed and power efficiency.',
    features: ['Liquid Retina display', '1080p FaceTime HD camera', 'MagSafe 3 charging'],
    tags: ['laptop', 'apple', 'macbook', 'macos'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 3100 },
  },
  {
    id: 'P1008',
    slug: 'samsung-galaxy-watch-6',
    name: 'Samsung Galaxy Watch 6',
    brand: 'Samsung',
    category: 'Tech',
    subcategory: 'Wearables',
    image: 'https://images.unsplash.com/photo-1544117519-31a4b719223d?q=80&w=800&auto=format&fit=crop',
    quantity: 60,
    price: { original: 33999, discounted: 29999, currency: '₹' },
    specifications: { Display: 'Super AMOLED', OS: 'Wear OS', 'Case Size': '44mm' },
    shortDescription: 'Track your wellness and fitness journey right from your wrist.',
    description: 'The Galaxy Watch 6 features a bigger screen, personalized heart rate zones, and advanced sleep tracking.',
    features: ['Sleep coaching', 'Body composition analysis', 'Durable crystal glass'],
    tags: ['smartwatch', 'wearable', 'samsung', 'android'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 1400 },
  },
  {
    id: 'P1009',
    slug: 'bose-quietcomfort-earbuds-2',
    name: 'Bose QuietComfort Earbuds II',
    brand: 'Bose',
    category: 'Tech',
    subcategory: 'Audio',
    image: 'https://images.unsplash.com/photo-1629098254203-97995a782b7c?q=80&w=800&auto=format&fit=crop',
    quantity: 50,
    price: { original: 25900, currency: '₹' },
    specifications: { Connectivity: 'Bluetooth 5.3', 'Noise Cancelling': 'CustomTune technology', 'Battery Life': '6 hours' },
    shortDescription: 'The world’s best noise cancellation and tailored sound.',
    description: 'These next-generation wireless earbuds are engineered for a listening experience that’s all you. With CustomTune technology, they personalize the noise cancellation and sound performance to your ears.',
    features: ['Aware Mode', 'Simple touch controls', 'Secure and comfortable fit'],
    tags: ['earbuds', 'audio', 'bose', 'noise-cancelling'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 2800 },
  },
  {
    id: 'P1010',
    slug: 'logitech-mx-master-3s-mouse',
    name: 'Logitech MX Master 3S',
    brand: 'Logitech',
    category: 'Tech',
    subcategory: 'Accessories',
    image: 'https://images.unsplash.com/photo-1615663245642-9904791cd90f?q=80&w=800&auto=format&fit=crop',
    quantity: 100,
    price: { original: 10995, discounted: 9995, currency: '₹' },
    specifications: { Sensor: '8K DPI optical sensor', Connectivity: 'Bluetooth, Logi Bolt USB', 'Buttons': '7' },
    shortDescription: 'An icon remastered for performance and ergonomics.',
    description: 'The MX Master 3S is an iconic mouse remastered. Experience ultimate comfort and performance with quiet clicks and an 8,000 DPI track-on-glass sensor.',
    features: ['MagSpeed electromagnetic scrolling', 'App-specific customizations', 'Flow cross-computer control'],
    tags: ['mouse', 'accessory', 'logitech', 'productivity'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 4200 },
  },
  {
    id: 'P2004',
    slug: 'levis-501-original-fit-jeans',
    name: 'Levi\'s 501 Original Fit Jeans',
    brand: 'Levi\'s',
    category: 'Fashion',
    subcategory: 'Men-Casual',
    image: 'https://images.unsplash.com/photo-1604176354204-926873782855?q=80&w=800&auto=format&fit=crop',
    quantity: 80,
    price: { original: 3999, currency: '₹' },
    specifications: { Material: '100% Cotton', Fit: 'Original Fit', 'Waist Rise': 'Sits at waist' },
    shortDescription: 'The iconic blue jean that started it all.',
    description: 'The original blue jean since 1873. The 501 Original is the blueprint for every pair of jeans in existence — burned into the world’s collective cortex ever since Levi Strauss invented them.',
    features: ['Button fly', '5-pocket styling', 'Signature Levi\'s tab'],
    tags: ['jeans', 'denim', 'men', 'levis', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 8500 },
  },
  {
    id: 'P2005',
    slug: 'womens-floral-a-line-dress',
    name: 'Women\'s Floral A-Line Dress',
    brand: 'Zara',
    category: 'Fashion',
    subcategory: 'Women-Western',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=800&auto=format&fit=crop',
    quantity: 60,
    price: { original: 3590, discounted: 2990, currency: '₹' },
    specifications: { Material: 'Viscose', 'Neckline': 'V-Neck', 'Sleeve Style': 'Puff Sleeve' },
    shortDescription: 'A breezy and beautiful floral dress for any occasion.',
    description: 'Embrace a touch of romance with this stunning floral A-line dress. Its lightweight fabric and flattering silhouette make it perfect for brunches, picnics, or a casual day out.',
    features: ['Elasticated cuffs', 'Lined interior', 'Tie-up detail at back'],
    tags: ['dress', 'floral', 'women', 'zara', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 750 },
  },
  {
    id: 'P2006',
    slug: 'adidas-ultraboost-running-shoes',
    name: 'Adidas Ultraboost Running Shoes',
    brand: 'Adidas',
    category: 'Fashion',
    subcategory: 'Footwear',
    image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=800&auto=format&fit=crop',
    quantity: 90,
    price: { original: 17999, currency: '₹' },
    specifications: { 'Upper Material': 'Primeknit', 'Midsole': 'Boost', 'Use': 'Running, Lifestyle' },
    shortDescription: 'Incredible energy return for your daily runs.',
    description: 'These running shoes combine comfort and high-performance technology for a best-ever-run feeling. They have a foot-hugging knit upper and a responsive Boost midsole.',
    features: ['Sock-like fit', 'Continental Rubber outsole', 'Supportive heel counter'],
    tags: ['sneakers', 'shoes', 'running', 'adidas', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 6200 },
  },
  {
    id: 'P2007',
    slug: 'ray-ban-aviator-classic-sunglasses',
    name: 'Ray-Ban Aviator Classic Sunglasses',
    brand: 'Ray-Ban',
    category: 'Fashion',
    subcategory: 'Accessories',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=800&auto=format&fit=crop',
    quantity: 120,
    price: { original: 13090, currency: '₹' },
    specifications: { 'Frame Material': 'Metal', 'Lens Color': 'Green Classic G-15', 'Shape': 'Pilot' },
    shortDescription: 'Timeless style that has been a favorite for generations.',
    description: 'Currently one of the most iconic sunglass models in the world, Ray-Ban Aviator Classic sunglasses were originally designed for U.S. aviators in 1937.',
    features: ['100% UV protection', 'Classic pilot shape', 'Lightweight frame'],
    tags: ['sunglasses', 'accessory', 'ray-ban', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 9800 },
  },
  {
    id: 'P3003',
    slug: 'himalaya-neem-face-wash-150ml',
    name: 'Himalaya Purifying Neem Face Wash (150ml)',
    brand: 'Himalaya',
    category: 'Ayurvedic',
    subcategory: 'Personal-Care',
    image: 'https://images.unsplash.com/photo-1629198735660-e39ea79d5e38?q=80&w=800&auto=format&fit=crop',
    quantity: 200,
    price: { original: 170, currency: '₹' },
    specifications: { 'Key Ingredients': 'Neem, Turmeric', 'Skin Type': 'All Skin Types' },
    shortDescription: 'Prevents pimples and purifies skin.',
    description: 'Himalaya\'s Purifying Neem Face Wash is a soap-free, herbal formulation that cleans impurities and helps clear pimples. A natural blend of Neem and Turmeric bring together their antibacterial and antifungal properties.',
    features: ['Soap-free formula', 'Hypoallergenic', 'Clinically tested'],
    tags: ['facewash', 'neem', 'himalaya', 'ayurvedic', 'skincare'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 15000 },
  },
  {
    id: 'P3004',
    slug: 'dabur-chyawanprash-1kg',
    name: 'Dabur Chyawanprash (1kg)',
    brand: 'Dabur',
    category: 'Ayurvedic',
    subcategory: 'Supplements',
    image: 'https://images.unsplash.com/photo-1591185854599-0734914c814b?q=80&w=800&auto=format&fit=crop',
    quantity: 150,
    price: { original: 410, discounted: 375, currency: '₹' },
    specifications: { 'Base Ingredient': 'Amla', 'Form': 'Paste' },
    shortDescription: 'Ayurvedic immunity booster for the whole family.',
    description: 'Dabur Chyawanprash is a time-tested Ayurvedic formulation of more than 41 Ayurvedic herbs that aid in boosting the immune system, thereby protecting the body from everyday infections.',
    features: ['Derived from a 2500-year-old formula', 'Rich in antioxidants', 'Clinically proven to boost immunity'],
    tags: ['chyawanprash', 'immunity', 'dabur', 'ayurvedic'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 12500 },
  },
  {
    id: 'P4001',
    slug: 'prestige-pressure-cooker-5l',
    name: 'Prestige Popular Aluminium Pressure Cooker (5 Litre)',
    brand: 'Prestige',
    category: 'Home',
    subcategory: 'Kitchenware',
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=800&auto=format&fit=crop',
    quantity: 80,
    price: { original: 1775, currency: '₹' },
    specifications: { 'Material': 'Aluminium', 'Capacity': '5 Litres', 'Base': 'Induction Base' },
    shortDescription: 'The perfect pressure cooker for fast and efficient cooking.',
    description: 'The Prestige Popular pressure cooker is one of the most popular pressure cookers from Prestige. It is designed for durability and safety, with an induction compatible base.',
    features: ['Precision weight valve', 'Comfortable handles', 'Metallic safety plug'],
    tags: ['kitchen', 'cookware', 'prestige', 'home'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 18000 },
  },
  {
    id: 'P4002',
    slug: 'philips-steam-iron-gc1905',
    name: 'Philips Steam Iron GC1905',
    brand: 'Philips',
    category: 'Home',
    subcategory: 'Appliances',
    image: 'https://images.unsplash.com/photo-1576426863848-c21f68c6aa98?q=80&w=800&auto=format&fit=crop',
    quantity: 100,
    price: { original: 1595, discounted: 1399, currency: '₹' },
    specifications: { 'Power': '1440 W', 'Soleplate': 'American Heritage Black Linished', 'Continuous Steam': '17 g/min' },
    shortDescription: 'Powerful steam iron for quick and easy crease removal.',
    description: 'This easy-to-use Philips steam iron helps to speed up your ironing. It features a continuous steam output and a finely pointed tip for getting into tricky areas.',
    features: ['Easy-fill water tank', 'Calc-clean function', 'Even steam distribution'],
    tags: ['iron', 'appliance', 'philips', 'home'],
    inventory: { inStock: true },
    ratings: { average: 4.4, count: 9500 },
  },
  {
    id: 'P4003',
    slug: 'wipro-smart-led-bulb-9w',
    name: 'Wipro 9W B22D Wi-Fi Smart LED Bulb',
    brand: 'Wipro',
    category: 'Home',
    subcategory: 'Smart-Home',
    image: 'https://images.unsplash.com/photo-1595152772103-b09e6973dd19?q=80&w=800&auto=format&fit=crop',
    quantity: 120,
    price: { original: 899, discounted: 649, currency: '₹' },
    specifications: { 'Wattage': '9 Watts', 'Connector': 'B22D', 'Color': '16 Million Colors (RGB)' },
    shortDescription: 'Make your home smarter with this Wi-Fi enabled LED bulb.',
    description: 'Control your lighting from anywhere with the Wipro Smart Home App. Choose from 16 million colors and set schedules and timers to automate your lighting.',
    features: ['Voice control with Alexa & Google Assistant', 'Dimmable', 'No hub required'],
    tags: ['smart-bulb', 'led', 'wipro', 'home'],
    inventory: { inStock: true },
    ratings: { average: 4.3, count: 7800 },
  },
  {
    id: 'P5001',
    slug: 'lakme-eyeconic-kajal-deep-black',
    name: 'Lakmé Eyeconic Kajal, Deep Black',
    brand: 'Lakmé',
    category: 'Beauty',
    subcategory: 'Makeup',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=800&auto=format&fit=crop',
    quantity: 300,
    price: { original: 180, currency: '₹' },
    specifications: { 'Shade': 'Deep Black', 'Lasting Power': 'Up to 22 hours', 'Formulation': 'Smudge-proof' },
    shortDescription: 'Intense black kajal that defines your eyes beautifully.',
    description: 'Accentuate the beauty of your eyes with the Lakmé Eyeconic Kajal. This dermatologically tested kajal is just what you need for completing your eye makeup or carrying a simple, only-kajal look. It\'s a smudge-proof, waterproof kajal.',
    features: ['Waterproof', 'Dermatologically tested', 'Twist-up format'],
    tags: ['kajal', 'eyeliner', 'lakme', 'beauty', 'makeup'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 25000 },
  },
  {
    id: 'P5002',
    slug: 'neutrogena-sunscreen-spf50',
    name: 'Neutrogena Ultra Sheer Sunscreen SPF 50+',
    brand: 'Neutrogena',
    category: 'Beauty',
    subcategory: 'Skincare',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop',
    quantity: 180,
    price: { original: 650, discounted: 550, currency: '₹' },
    specifications: { 'SPF': '50+', 'Skin Type': 'All Skin Types', 'Form': 'Lotion' },
    shortDescription: 'Broad spectrum UVA/UVB protection with a weightless feel.',
    description: 'Neutrogena Ultra Sheer Dry-Touch Sunscreen provides superior broad-spectrum protection against skin-aging UVA and burning UVB rays, and combines it with Dry-Touch technology for a lightweight, clean feel.',
    features: ['Oil-free', 'PABA-free', 'Non-comedogenic (won\'t clog pores)'],
    tags: ['sunscreen', 'skincare', 'neutrogena', 'beauty'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 11000 },
  },
  {
    id: 'P6001',
    slug: 'tata-salt-1kg',
    name: 'Tata Salt (1kg)',
    brand: 'Tata',
    category: 'Groceries',
    subcategory: 'Staples',
    image: 'https://images.unsplash.com/photo-1516594798947-7b7385a53852?q=80&w=800&auto=format&fit=crop',
    quantity: 500,
    price: { original: 28, currency: '₹' },
    specifications: { 'Type': 'Iodized Salt', 'Weight': '1kg' },
    shortDescription: 'India\'s first and most trusted iodized salt brand.',
    description: 'Tata Salt is a vacuum-evaporated iodised salt that supplies iodine, a vital micronutrient. It ensures the purity and right amount of iodine in the salt.',
    features: ['Contains requisite amount of iodine', 'Vacuum evaporated', 'Pure and white'],
    tags: ['salt', 'staple', 'tata', 'groceries'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 35000 },
  },
  {
    id: 'P6002',
    slug: 'aashirvaad-atta-5kg',
    name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    brand: 'Aashirvaad',
    category: 'Groceries',
    subcategory: 'Staples',
    image: 'https://images.unsplash.com/photo-1607584149959-338a9a2a7e4b?q=80&w=800&auto=format&fit=crop',
    quantity: 250,
    price: { original: 245, currency: '₹' },
    specifications: { 'Type': 'Whole Wheat Atta', 'Weight': '5kg' },
    shortDescription: 'Made from the choicest grains for soft, fluffy rotis.',
    description: 'Aashirvaad Shudh Chakki Atta is made from the choicest grains - heavy on the palm, golden amber in colour and hard in bite. It is carefully ground using modern \'chakki - grinding\' process which ensures that it contains 0% Maida and 100% Sampoorna Atta.',
    features: ['100% Sampoorna Atta', '0% Maida', 'Absorbs more water for softer rotis'],
    tags: ['atta', 'flour', 'staple', 'aashirvaad', 'groceries'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 28000 },
  },
  {
    id: 'P6003',
    slug: 'maggi-2-minute-noodles-560g',
    name: 'Maggi 2-Minute Noodles Masala (560g)',
    brand: 'Maggi',
    category: 'Groceries',
    subcategory: 'Snacks',
    image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?q=80&w=800&auto=format&fit=crop',
    quantity: 400,
    price: { original: 108, currency: '₹' },
    specifications: { 'Flavor': 'Masala', 'Weight': '560g (8-pack)' },
    shortDescription: 'Your favorite instant noodles, ready in just 2 minutes.',
    description: 'MAGGI 2-Minute Masala Noodles is a brand of instant noodles manufactured by Nestlé. It is made with the finest quality spices and ingredients. Each portion provides 15% of your daily iron requirement.',
    features: ['Goodness of Iron', 'Contains a blend of 10 spices', 'Quick and easy to make'],
    tags: ['noodles', 'maggi', 'snack', 'groceries'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 45000 },
  },
  {
    id: 'P1011',
    slug: 'hp-pavilion-gaming-laptop',
    name: 'HP Pavilion Gaming Laptop (Ryzen 5)',
    brand: 'HP',
    category: 'Tech',
    subcategory: 'Laptops',
    image: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?q=80&w=800&auto=format&fit=crop',
    quantity: 25,
    price: { original: 75000, discounted: 68000, currency: '₹' },
    specifications: { 'Processor': 'AMD Ryzen 5', 'Graphics': 'NVIDIA GTX 1650', 'RAM': '8 GB' },
    shortDescription: 'A thin and powerful gaming laptop.',
    description: 'Sacrifice nothing with the thin and powerful HP Pavilion Gaming Laptop. Experience high-grade graphics and processing power for gaming and multitasking, plus improved thermal cooling.',
    features: ['Micro-edge display', 'B&O Audio', 'Backlit keyboard'],
    tags: ['laptop', 'gaming', 'hp', 'tech'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 2300 },
  },
  {
    id: 'P1012',
    slug: 'jbl-flip-5-bluetooth-speaker',
    name: 'JBL Flip 5 Portable Bluetooth Speaker',
    brand: 'JBL',
    category: 'Tech',
    subcategory: 'Audio',
    image: 'https://images.unsplash.com/photo-1589101284727-b5278c2818aa?q=80&w=800&auto=format&fit=crop',
    quantity: 70,
    price: { original: 9999, discounted: 8499, currency: '₹' },
    specifications: { 'Connectivity': 'Bluetooth 4.2', 'Battery Life': '12 hours', 'Waterproof': 'IPX7' },
    shortDescription: 'Sounds better than ever. Feel your music.',
    description: 'Take your tunes on the go with the powerful JBL Flip 5. Our lightweight Bluetooth speaker goes anywhere. Bad weather? Not to worry. With its waterproof design, you can rock out to our signature sound rain or shine.',
    features: ['PartyBoost compatible', 'Durable fabric material', 'Racetrack-shaped driver'],
    tags: ['speaker', 'bluetooth', 'jbl', 'audio'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 8800 },
  },
  {
    id: 'P2008',
    slug: 'puma-mens-running-shoes',
    name: 'Puma Men\'s Softride Rift Running Shoes',
    brand: 'Puma',
    category: 'Fashion',
    subcategory: 'Footwear',
    image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=800&auto=format&fit=crop',
    quantity: 110,
    price: { original: 4999, discounted: 2499, currency: '₹' },
    specifications: { 'Upper Material': 'Mesh', 'Midsole': 'SoftFoam+', 'Use': 'Running, Training' },
    shortDescription: 'Extreme cushioning and all-day comfort.',
    description: 'The Softride Rift is one of PUMA’s most comfortable styles. With a full-length Softride midsole, this shoe will keep you light on your feet for an all-day cushioned feel.',
    features: ['Easy slip-on construction', 'Zoned rubber outsole for traction', 'Bold PUMA branding'],
    tags: ['sneakers', 'shoes', 'puma', 'fashion'],
    inventory: { inStock: true },
    ratings: { average: 4.4, count: 3200 },
  },
  {
    id: 'P3005',
    slug: 'organic-india-tulsi-green-tea',
    name: 'Organic India Tulsi Green Tea Classic (25 Bags)',
    brand: 'Organic India',
    category: 'Ayurvedic',
    subcategory: 'Herbal-Powders',
    image: 'https://images.unsplash.com/photo-1578852632225-17a4c48a472c?q=80&w=800&auto=format&fit=crop',
    quantity: 150,
    price: { original: 210, currency: '₹' },
    specifications: { 'Ingredients': 'Green Tea, Rama Tulsi, Krishna Tulsi, Vana Tulsi', 'Form': 'Tea Bags' },
    shortDescription: 'A harmonious blend of Tulsi and Green Tea.',
    description: 'A delightful combination of Tulsi and Green Tea, this tea is a rich source of antioxidants. It helps in reducing stress, improving metabolism and boosting stamina.',
    features: ['Stress relieving', 'Rich in antioxidants', 'USDA Organic certified'],
    tags: ['tea', 'green-tea', 'tulsi', 'ayurvedic', 'organic'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 6700 },
  },
  {
    id: 'P4004',
    slug: 'milton-thermosteel-flask-1l',
    name: 'Milton Thermosteel Flip Lid Flask (1 Litre)',
    brand: 'Milton',
    category: 'Home',
    subcategory: 'Kitchenware',
    image: 'https://images.unsplash.com/photo-1616168393587-70362145e149?q=80&w=800&auto=format&fit=crop',
    quantity: 90,
    price: { original: 1050, discounted: 899, currency: '₹' },
    specifications: { 'Material': 'Stainless Steel', 'Capacity': '1 Litre', 'Insulation': 'Double Walled Vacuum' },
    shortDescription: 'Keeps beverages hot or cold for 24 hours.',
    description: 'This sturdy stainless steel flask from Milton is designed to keep your beverages hot or cold for hours. It comes with a convenient flip lid for easy sipping.',
    features: ['100% Leak proof', 'Rust proof', 'Easy to carry'],
    tags: ['flask', 'thermos', 'milton', 'home', 'kitchen'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 21000 },
  },
  {
    id: 'P5003',
    slug: 'loreal-paris-shampoo-650ml',
    name: 'L\'Oréal Paris Total Repair 5 Shampoo (650ml)',
    brand: 'L\'Oréal Paris',
    category: 'Beauty',
    subcategory: 'Hair-Care',
    image: 'https://images.unsplash.com/photo-1585779034823-7e9ac8faec70?q=80&w=800&auto=format&fit=crop',
    quantity: 130,
    price: { original: 599, discounted: 449, currency: '₹' },
    specifications: { 'Hair Type': 'Damaged Hair', 'Volume': '650ml', 'Action': 'Repairs 5 signs of damage' },
    shortDescription: 'Fights the 5 signs of damaged hair.',
    description: 'L\'Oréal Paris Total Repair 5 shampoo helps fight against the five visible signs of damaged hair - hair fall, dryness, roughness, dullness, and split ends without weighing it down.',
    features: ['Ceramide-Cement technology', 'For stronger, smoother hair', 'Reduces breakage'],
    tags: ['shampoo', 'hair-care', 'loreal', 'beauty'],
    inventory: { inStock: true },
    ratings: { average: 4.4, count: 19000 },
  },
  {
    id: 'P6004',
    slug: 'britannia-good-day-cashew-cookies',
    name: 'Britannia Good Day Cashew Cookies (600g)',
    brand: 'Britannia',
    category: 'Groceries',
    subcategory: 'Snacks',
    image: 'https://images.unsplash.com/photo-1580643788157-5bb8d1a1b5d1?q=80&w=800&auto=format&fit=crop',
    quantity: 300,
    price: { original: 140, currency: '₹' },
    specifications: { 'Flavor': 'Cashew', 'Weight': '600g' },
    shortDescription: 'Loaded with the richness of cashew nuts.',
    description: 'With its delectable aroma and crunchy cookie bite, the Good Day Cashew cookie is a favorite of all. It\'s a smile that makes your day.',
    features: ['Rich in butter', 'Melt-in-your-mouth experience', 'Perfect tea-time snack'],
    tags: ['cookies', 'biscuits', 'britannia', 'groceries', 'snack'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 22000 },
  },
  {
    id: 'P1013',
    slug: 'apple-ipad-10th-gen',
    name: 'Apple iPad (10th Generation)',
    brand: 'Apple',
    category: 'Tech',
    subcategory: 'Tablets',
    image: 'https://images.unsplash.com/photo-1587280501635-3c0700160249?q=80&w=800&auto=format&fit=crop',
    quantity: 35,
    price: { original: 44900, currency: '₹' },
    specifications: { 'Chip': 'A14 Bionic', 'Display': '10.9-inch Liquid Retina', 'Storage': '64 GB' },
    shortDescription: 'Lovable. Drawable. Magical.',
    description: 'The all-new iPad is colorfully redesigned to be more capable, more intuitive, and even more fun. With a new all‑screen design, 10.9-inch Liquid Retina display, and four gorgeous colors.',
    features: ['Works with Apple Pencil (1st gen)', 'Landscape 12MP Ultra Wide front camera', 'Wi-Fi 6'],
    tags: ['tablet', 'ipad', 'apple', 'tech'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 1800 },
  },
  {
    id: 'P2009',
    slug: 'women-silk-banarasi-saree',
    name: 'Women\'s Art Silk Banarasi Saree',
    brand: 'EthnicVibes',
    category: 'Fashion',
    subcategory: 'Women-Ethnic',
    image: 'https://images.unsplash.com/photo-1610192534099-0743b10c5c3c?q=80&w=800&auto=format&fit=crop',
    quantity: 40,
    price: { original: 4999, discounted: 1999, currency: '₹' },
    specifications: { 'Material': 'Art Silk', 'Work': 'Zari Woven', 'Includes': 'Saree with Blouse Piece' },
    shortDescription: 'A beautiful saree for festive occasions and weddings.',
    description: 'This elegant Banarasi art silk saree features intricate zari work all over. It comes with a matching blouse piece and is perfect for traditional events.',
    features: ['Rich pallu', 'Soft and easy to drape', 'Traditional design'],
    tags: ['saree', 'banarasi', 'ethnic', 'fashion', 'women'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 1250 },
  },
  {
    id: 'P3006',
    slug: 'patanjali-honey-1kg',
    name: 'Patanjali Honey (1kg)',
    brand: 'Patanjali',
    category: 'Ayurvedic',
    subcategory: 'Supplements',
    image: 'https://images.unsplash.com/photo-1558642144-3c82255d6b38?q=80&w=800&auto=format&fit=crop',
    quantity: 180,
    price: { original: 400, currency: '₹' },
    specifications: { 'Type': 'Natural Honey', 'Weight': '1kg' },
    shortDescription: 'A pure and natural source of energy.',
    description: 'Patanjali Honey is rich in fructose, minerals, vitamins, and other nutritious elements. It is a good quality honey and is a good source of energy.',
    features: ['Rich in antioxidants', 'Natural sweetener', 'Boosts immunity'],
    tags: ['honey', 'patanjali', 'ayurvedic', 'supplement'],
    inventory: { inStock: true },
    ratings: { average: 4.4, count: 9800 },
  },
  {
    id: 'P4005',
    slug: 'dyson-v11-vacuum-cleaner',
    name: 'Dyson V11 Absolute Pro Cord-Free Vacuum',
    brand: 'Dyson',
    category: 'Home',
    subcategory: 'Appliances',
    image: 'https://images.unsplash.com/photo-1569799291121-789a7f3b610c?q=80&w=800&auto=format&fit=crop',
    quantity: 15,
    price: { original: 59900, currency: '₹' },
    specifications: { 'Motor': 'Dyson Hyperdymium', 'Run time': 'Up to 60 minutes', 'Bin volume': '0.76 L' },
    shortDescription: 'Intelligently cleans, with twice the suction of any cord-free vac.',
    description: 'Dyson\'s most powerful, intelligent cord-free vacuum. It has a high-torque cleaner head that automatically adapts to different floor types.',
    features: ['LCD screen reports performance in real time', 'Point and shoot hygienic bin emptying', 'Whole-machine filtration'],
    tags: ['vacuum', 'dyson', 'appliance', 'home'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 3200 },
  },
  {
    id: 'P5004',
    slug: 'nivea-body-lotion-400ml',
    name: 'Nivea Nourishing Body Milk Lotion (400ml)',
    brand: 'Nivea',
    category: 'Beauty',
    subcategory: 'Skincare',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    quantity: 220,
    price: { original: 425, discounted: 319, currency: '₹' },
    specifications: { 'Skin Type': 'Very Dry Skin', 'Volume': '400ml', 'Key Ingredient': 'Almond Oil' },
    shortDescription: 'Intensive moisture care for 48 hours.',
    description: 'The Nivea Nourishing Body Milk is a richly caring body lotion for very dry skin. It is infused with the Nivea Deep Moisture Serum and 2x almond oil to nourish and intensively moisturize.',
    features: ['48h intensive moisture', 'Dermatologically approved', 'Non-greasy formula'],
    tags: ['body-lotion', 'skincare', 'nivea', 'beauty'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 17000 },
  },
  {
    id: 'P6005',
    slug: 'bru-instant-coffee-200g',
    name: 'Bru Instant Coffee (200g)',
    brand: 'Bru',
    category: 'Groceries',
    subcategory: 'Beverages',
    image: 'https://images.unsplash.com/photo-1511920183353-3c9c9b04d249?q=80&w=800&auto=format&fit=crop',
    quantity: 280,
    price: { original: 340, currency: '₹' },
    specifications: { 'Type': 'Instant Coffee', 'Weight': '200g Jar' },
    shortDescription: 'Authentic taste of coffee in every sip.',
    description: 'Bru Instant Coffee was launched in 1968 and was India’s first coffee-chicory mix instant coffee. It is made from a fine blend of the choicest plantation and Robusta beans.',
    features: ['Perfect mix of 70% coffee and 30% chicory', 'Rich aroma', 'Soluble coffee powder'],
    tags: ['coffee', 'bru', 'beverage', 'groceries'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 14000 },
  },
   {
    id: 'P1014',
    slug: 'canon-eos-1500d-dslr',
    name: 'Canon EOS 1500D DSLR Camera',
    brand: 'Canon',
    category: 'Tech',
    subcategory: 'Cameras',
    image: 'https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?q=80&w=800&auto=format&fit=crop',
    quantity: 20,
    price: { original: 41995, discounted: 38990, currency: '₹' },
    specifications: { 'Sensor': '24.1MP APS-C CMOS', 'Connectivity': 'Wi-Fi, NFC', 'Lens': 'EF-S 18-55mm' },
    shortDescription: 'A perfect first DSLR for aspiring photographers.',
    description: 'The EOS 1500D is a user-friendly DSLR that captures beautiful images and movies with background blur. It\'s equipped with a 24.1-megapixel sensor and Wi-Fi/NFC for easy sharing.',
    features: ['Scene Intelligent Auto mode', 'Full HD video recording', '9-point autofocus'],
    tags: ['camera', 'dslr', 'canon', 'tech'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 5600 },
  },
  {
    id: 'P2010',
    slug: 'men-formal-shirt-peter-england',
    name: 'Peter England Men\'s Slim Fit Formal Shirt',
    brand: 'Peter England',
    category: 'Fashion',
    subcategory: 'Men-Formal',
    image: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=800&auto=format&fit=crop',
    quantity: 150,
    price: { original: 1799, discounted: 1299, currency: '₹' },
    specifications: { 'Material': 'Cotton Blend', 'Fit': 'Slim Fit', 'Color': 'Light Blue' },
    shortDescription: 'A crisp and smart shirt for the modern professional.',
    description: 'Look your best at work with this stylish slim-fit formal shirt from Peter England. Made from a comfortable cotton blend, it ensures you stay sharp all day.',
    features: ['Cutaway collar', 'Long sleeves', 'Easy to iron'],
    tags: ['shirt', 'formal', 'peter-england', 'fashion', 'men'],
    inventory: { inStock: true },
    ratings: { average: 4.4, count: 4800 },
  },
  {
    id: 'P4006',
    slug: 'amazon-echo-dot-4th-gen',
    name: 'Amazon Echo Dot (4th Gen)',
    brand: 'Amazon',
    category: 'Home',
    subcategory: 'Smart-Home',
    image: 'https://images.unsplash.com/photo-1627993202957-63b7c88a38ba?q=80&w=800&auto=format&fit=crop',
    quantity: 100,
    price: { original: 4499, discounted: 3999, currency: '₹' },
    specifications: { 'Speaker': '1.6" front-firing', 'Connectivity': 'Wi-Fi, Bluetooth', 'Assistant': 'Alexa' },
    shortDescription: 'Smart speaker with a new spherical design and improved bass.',
    description: 'Our most popular smart speaker now comes in a refreshed, compact design that fits perfectly into small spaces. It delivers crisp vocals and balanced bass for full sound.',
    features: ['Control smart home devices', 'Stream music', 'Ask Alexa questions'],
    tags: ['smart-speaker', 'alexa', 'amazon', 'home'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 35000 },
  },
  {
    id: 'P6006',
    slug: 'fortune-sunflower-oil-5l',
    name: 'Fortune Sunlite Refined Sunflower Oil (5L Can)',
    brand: 'Fortune',
    category: 'Groceries',
    subcategory: 'Oils',
    image: 'https://images.unsplash.com/photo-1625245358223-1a20f964a78c?q=80&w=800&auto=format&fit=crop',
    quantity: 120,
    price: { original: 850, currency: '₹' },
    specifications: { 'Type': 'Refined Sunflower Oil', 'Volume': '5 Litres' },
    shortDescription: 'A light and healthy cooking oil for your family.',
    description: 'Fortune Sunlite Sunflower Oil is a light, healthy and nutritious cooking oil. Being rich in vitamins and consisting mainly of polyunsaturated fatty acids, it makes food easy to digest.',
    features: ['Rich in Vitamin E', 'Light and easy to digest', 'Helps in reducing cholesterol'],
    tags: ['oil', 'cooking-oil', 'fortune', 'groceries'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 12000 },
  },
  {
    id: 'P2011',
    slug: 'fastrack-reflex-smart-band',
    name: 'Fastrack Reflex VOX Smart Band',
    brand: 'Fastrack',
    category: 'Tech',
    subcategory: 'Wearables',
    image: 'https://images.unsplash.com/photo-1579586337278-35f4b7ebd136?q=80&w=800&auto=format&fit=crop',
    quantity: 90,
    price: { original: 4995, discounted: 2495, currency: '₹' },
    specifications: { 'Display': '1.69" Large Display', 'Features': 'Alexa Built-in, HR & SpO2 Monitor', 'Battery': 'Up to 10 days' },
    shortDescription: 'Your stylish fitness partner with a large display and Alexa.',
    description: 'The Fastrack Reflex VOX is more than just a fitness band. With a large touch display, built-in Alexa, heart rate and SpO2 monitor, it is the perfect companion for your fitness journey.',
    features: ['100+ watch faces', 'Music & camera control', 'Sleep & stress monitor'],
    tags: ['smart-band', 'fitness-tracker', 'fastrack', 'tech', 'wearable'],
    inventory: { inStock: true },
    ratings: { average: 4.2, count: 6500 },
  },
  {
    id: 'P4007',
    slug: 'kent-grand-plus-ro-water-purifier',
    name: 'KENT Grand+ RO+UV+UF+TDS Water Purifier',
    brand: 'KENT',
    category: 'Home',
    subcategory: 'Appliances',
    image: 'https://images.unsplash.com/photo-1617834938637-a14878a9c388?q=80&w=800&auto=format&fit=crop',
    quantity: 30,
    price: { original: 20000, discounted: 18500, currency: '₹' },
    specifications: { 'Technology': 'RO+UV+UF+TDS Control', 'Storage Capacity': '9 Litres', 'Purification Capacity': '20 L/hr' },
    shortDescription: 'Makes water 100% pure and safe for drinking.',
    description: 'KENT Grand+ uses multiple purification process of RO+UV+UF+TDS Control to remove dissolved impurities, bacteria & viruses to make water 100% pure. It also retains essential natural minerals in the purified water.',
    features: ['Mineral RO Technology', 'In-tank UV disinfection', 'Water level indicator'],
    tags: ['water-purifier', 'kent', 'appliance', 'home'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 11500 },
  },
  {
    id: 'P6007',
    slug: 'cadbury-dairy-milk-silk-chocolate',
    name: 'Cadbury Dairy Milk Silk Chocolate Bar (150g)',
    brand: 'Cadbury',
    category: 'Groceries',
    subcategory: 'Snacks',
    image: 'https://images.unsplash.com/photo-1625244569833-280b06b523f7?q=80&w=800&auto=format&fit=crop',
    quantity: 500,
    price: { original: 175, currency: '₹' },
    specifications: { 'Type': 'Milk Chocolate', 'Weight': '150g' },
    shortDescription: 'The classic taste of Cadbury chocolates, only smoother.',
    description: 'Cadbury Dairy Milk Silk is all about regaling in the chocolate\'s richness and creaminess. The classic taste of Cadbury chocolates enriched with the real goodness of milk.',
    features: ['Smoother, creamier, and finer', 'Made from the finest cocoa beans', 'Perfect for sharing'],
    tags: ['chocolate', 'cadbury', 'silk', 'groceries', 'snack'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 32000 },
  },
  {
    id: 'P1015',
    slug: 'sandisk-ultra-128gb-microsd',
    name: 'SanDisk Ultra 128GB microSDXC Memory Card',
    brand: 'SanDisk',
    category: 'Tech',
    subcategory: 'Accessories',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=800&auto=format&fit=crop',
    quantity: 200,
    price: { original: 1500, discounted: 1099, currency: '₹' },
    specifications: { 'Capacity': '128 GB', 'Speed Class': 'Class 10, U1, A1', 'Read Speed': 'Up to 120 MB/s' },
    shortDescription: 'Ideal for Android smartphones and tablets.',
    description: 'The SanDisk Ultra microSD card gives you the freedom to shoot, save and share more. With capacities up to 1TB, it\'s perfect for recording and watching Full HD video.',
    features: ['Load apps faster with A1-rated performance', 'Durable design', 'Full HD video capture'],
    tags: ['memory-card', 'microsd', 'sandisk', 'tech', 'accessory'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 45000 },
  },
  {
    id: 'P2012',
    slug: 'woodland-mens-leather-boots',
    name: 'Woodland Men\'s Leather Boots',
    brand: 'Woodland',
    category: 'Fashion',
    subcategory: 'Footwear',
    image: 'https://images.unsplash.com/photo-1520622482312-d9f0a4f5f128?q=80&w=800&auto=format&fit=crop',
    quantity: 60,
    price: { original: 4595, currency: '₹' },
    specifications: { 'Material': 'Genuine Leather', 'Sole': 'Thermoplastic Rubber', 'Closure': 'Lace-Up' },
    shortDescription: 'Rugged and durable boots for the adventurer.',
    description: 'Crafted from high-quality leather, these Woodland boots are designed for comfort and durability. The rugged sole provides excellent grip, making them perfect for outdoor adventures.',
    features: ['High-ankle design', 'Cushioned insole', 'Anti-corrosive metal fittings'],
    tags: ['boots', 'leather', 'woodland', 'fashion', 'men'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 7800 },
  },
  {
    id: 'P3007',
    slug: 'baidyanath-giloy-juice-1l',
    name: 'Baidyanath Giloy Juice (1 Litre)',
    brand: 'Baidyanath',
    category: 'Ayurvedic',
    subcategory: 'Herbal-Powders',
    image: 'https://images.unsplash.com/photo-1631049354023-866d3a95f50f?q=80&w=800&auto=format&fit=crop',
    quantity: 90,
    price: { original: 350, currency: '₹' },
    specifications: { 'Ingredient': 'Giloy (Tinospora Cordifolia)', 'Volume': '1 Litre' },
    shortDescription: 'An Ayurvedic powerhouse to boost immunity.',
    description: 'Baidyanath Giloy Juice is extracted from fresh Giloy stems. Giloy is known as a powerhouse of antioxidants and helps boost immunity. It also helps in improving digestion and fighting respiratory problems.',
    features: ['100% pure and natural', 'No added sugar or flavor', 'Helps detoxify the body'],
    tags: ['giloy', 'juice', 'baidyanath', 'ayurvedic', 'immunity'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 5400 },
  }
]
